openapi: 3.0.0
info:
  version: 1.0.0
  title: Lockdown API
tags:
  - name: ByCountries
    description: Lockdown statuses operations by countries
  - name: World
    description: Lockdown statuses operations for whole world
paths:
  /status/world/{date}:
    get:
      tags:
        - World
      summary: Retrieve status of all countries with all NPIs
      parameters:
        - name: date
          description: Date of status snapshot
          in: path
          required: true
          default: 2020-04-27
          schema:
            type: string
            format: date
      responses:
        "200":
          description: "List of NPIs for date. Additional property is lockdown date."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    lockdown:
                      $ref: '#/components/schemas/Lockdown'
        default:
          description: Unexpected error
  /status/world/{startDate}/{endDate}:
    get:
      tags:
        - World
      summary: Retrieve status of all countries with all NPIs for date range
      parameters:
        - name: startDate
          description: Date of status snapshot
          in: path
          required: true
          default: 2020-04-27
          schema:
            type: string
            format: date
        - name: endDate
          description: Date of status snapshot. Date range not more than 70 days
          in: path
          required: true
          default: 2020-06-27
          schema:
            type: string
            format: date
      responses:
        "200":
          description: "List of NPIs for date. Additional property is lockdown date."
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    lockdown:
                      $ref: '#/components/schemas/Lockdown'
        default:
          description: Unexpected error
  /status/{iso}/{date}:
    get:
      tags:
        - Countries
      summary: "Retrieve status of the country with all NPIs"
      parameters:
        - name: iso
          in: path
          description: ISO2 or ISO3 country code
          required: true
          type: string
          default: IND
        - name: date
          description: Date of status snapshot
          in: path
          required: true
          default: 2020-04-27
          schema:
            type: string
            format: date
      responses:
        "200":
          description: "List of NPIs for date"
          content:
            application/json:
              schema:
                type: object
                properties:
                  lockdown:
                    $ref: '#/components/schemas/Lockdown'

        default:
          description: Unexpected error
  /status/{iso}/{startDate}/{endDate}:
    get:
      tags:
        - Countries
      summary: "Retrieve status of the country with all NPIs for date range"
      parameters:
        - name: iso
          in: path
          description: ISO2 or ISO3 country code
          required: true
          type: string
          default: IND
        - name: startDate
          description: Start Date of range
          in: path
          required: true
          default: 2020-04-27
          schema:
            type: string
            format: date
        - name: endDate
          description: End Date of range (range not more than 70 days)
          in: path
          required: true
          default: 2020-05-27
          schema:
            type: string
            format: date
      responses:
        "200":
          description: "List of NPIs for by date"
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    lockdown:
                      $ref: '#/components/schemas/Lockdown'
        default:
          description: Unexpected error
components:
  schemas:
    Measure:
      type: object
      required:
        - label
        - value
        - name
        - '#npi+num+max+gathering'
      properties:
        label:
          type: string
        name:
          type: string
        '#date+start':
          type: string
          format: date
        '#date+end':
          type: string
          format: date
        '#meta+url':
          type: string
        '#country+code+iso3':
          type: string
    Lockdown:
      type: object
      required: iso
      properties:
        iso:
          type: string
        measures:
          type: array
          items:
            $ref: '#/components/schemas/Measure'